# http://code.google.com/appengine/docs/python/config/appconfig.html

application: arbitnews
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: arbitnews.py

